Vagrant.configure("2") do |config|
  # Set VMware as the provider and define global resources
  config.vm.provider "vmware_desktop" do |vm|
    vm.memory = 2048
    vm.cpus = 2
    vm.gui = false
  end

  # Active Directory Domain Controller
  config.vm.define "addns01" do |addns|
    addns.vm.box = "gusztavvargadr/windows-server-2022-standard"
    addns.vm.hostname = "addns01"
    addns.vm.network "private_network", ip: "192.168.56.10"
    addns.vm.communicator = "winrm"
  end

  # Client 01 (Windows 10 Enterprise)
  config.vm.define "client01" do |client|
    client.vm.box = "gusztavvargadr/windows-10-22h2-enterprise"
    client.vm.hostname = "client01"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.communicator = "winrm"
  end

  # Client 02 (Windows 10 Enterprise)
  config.vm.define "client02" do |client|
    client.vm.box = "gusztavvargadr/windows-10-22h2-enterprise"
    client.vm.hostname = "client02"
    client.vm.network "private_network", ip: "192.168.56.12"
    client.vm.communicator = "winrm"
  end

  # Kali Linux Attacker Box
  config.vm.define "kali01" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "kali01"
    kali.vm.network "private_network", ip: "192.168.56.20"
    kali.vm.provider "vmware_desktop" do |vm|
      vm.memory = 3072
      vm.cpus = 2
      vm.gui = true
    end
  end
end
